Repository Subang-Study/devshare, pull requests merged in 2023-07, with the labels that each got.

#5 Feat/resumeld profile
  src/app/[resumeId]/(resumeId)/create/page.tsx
  src/app/[resumeId]/page.tsx
  src/app/auth/page.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/pages/api/resumeld/[createProfile].ts
Labels: documentation

#6 feat: 폼 컨텍스트를 활용해서 기술스택 폼 컴포넌트 구성
  src/app/globals.css
  src/components/client/Btn.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/types/resumeDataType.ts
Labels: enhancement

#7 feat: 이력서 크리에트 부분 리엑트 훅 폼 으로 고치는 중
  src/app/[resumeId]/(resumeId)/create/page.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserInfoForm.tsx
Labels: documentation

#9 이력서 프로필 부분 리엑트 훅 폼 으로 수정 & css 수정
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserInfoForm.tsx
Labels: documentation

#10 feat: form 구조 타입 수정
  src/components/client/auth/UserMenu.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/types/resumeDataType.ts
Labels: enhancement

#11 Feat/resumeld profile
  src/components/client/resumeld/UserImageUploadButton.jsx
  src/components/client/resumeld/UserInfoForm.tsx
Labels: documentation

#12 Feat/imageupload
  .eslintrc.json
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/app/[resumeId]/(resumeId)/create/page.tsx
  src/app/[resumeId]/page.tsx
  src/app/auth/page.tsx
  src/app/example/page.tsx
  src/app/font.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/client/Btn.tsx
  src/components/client/Logo.tsx
  src/components/client/auth/GithubLoginBtn.tsx
  src/components/client/auth/UserMenu.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/server/.gitkeep
  src/components/server/Experience.tsx
  src/components/server/ExperienceTitle.tsx
  src/components/server/Header.tsx
  src/components/server/Introduce.tsx
  src/components/server/Profile.tsx
  src/components/server/Skill.tsx
  src/components/server/Skillset.tsx
  src/components/server/Study.tsx
  src/components/server/Titlename.tsx
  src/components/server/main/ResumeCardLoad.tsx
  src/hooks/.gitkeep
  src/hooks/useOuterClick.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/exam.ts
  src/pages/api/example.ts
  src/pages/api/resumeld/[createProfile].ts
  src/pages/api/uploadImage/uploadUserImage.ts
  src/types/env.d.ts
  src/types/next-auth.d.ts
  src/types/resumeDataType.ts
  src/utils/.gitkeep
  src/utils/Session.tsx
  src/utils/database.ts
  tsconfig.json
Labels: enhancement

#14 feat: 이미지 업로드(백엔드) 구현
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/components/client/Btn.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/pages/api/uploadImage/uploadUserImage.ts
  src/types/env.d.ts
  src/types/resumeDataType.ts
  tsconfig.json
Labels: enhancement

#17 feat: 이력서 생성 api
  package-lock.json
  package.json
  src/components/client/auth/UserMenu.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserImageUploadButton.jsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/pages/api/resume/create.ts
  src/pages/api/resumeld/[createProfile].ts
Labels: enhancement

#18 feat: 유저프로필 수정 및 반응형 기능 추가
  src/app/[resumeId]/(resumeId)/create/page.tsx
  src/app/globals.css
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeld/UserImageUploadButton.jsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/server/Header.tsx
Labels: documentation

#19 Feat/resume api
  src/app/auth/page.tsx
  src/app/layout.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/ui/Btn.tsx
  src/components/client/ui/Logo.tsx
  src/components/server/Profile.tsx
  src/components/server/ui/Header.tsx
  src/pages/api/example.ts
  src/pages/api/resume/[resumeId].ts
Labels: enhancement

#20 feat: 프로필이미지업로드버튼 tsx 로 수정
  src/components/client/resumeld/UserImageUploadButton.tsx
  src/components/client/resumeld/UserInfoForm.tsx
Labels: documentation

#21 feat:데이트피커라이브러추가 및 컴포넌트 생성
  package-lock.json
  package.json
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/ui/DatePickerComponent.tsx
Labels: documentation

#22 Feat/resume api
  .eslintrc.json
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/app/[resumeId]/(resumeId)/create/page.tsx
  src/app/[resumeId]/page.tsx
  src/app/auth/page.tsx
  src/app/example/page.tsx
  src/app/font.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/page.tsx
  src/components/client/Btn.tsx
  src/components/client/auth/GithubLoginBtn.tsx
  src/components/client/auth/UserMenu.tsx
  src/components/client/main/ResumeCard.tsx
  src/components/client/main/ResumeCardList.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserImageUploadButton.jsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/client/ui/Btn.tsx
  src/components/client/ui/Logo.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/.gitkeep
  src/components/server/Experience.tsx
  src/components/server/ExperienceTitle.tsx
  src/components/server/Introduce.tsx
  src/components/server/Profile.tsx
  src/components/server/Skill.tsx
  src/components/server/Skillset.tsx
  src/components/server/Study.tsx
  src/components/server/Titlename.tsx
  src/components/server/main/ResumeCardLoad.tsx
  src/components/server/ui/Header.tsx
  src/hooks/.gitkeep
  src/hooks/useOuterClick.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/exam.ts
  src/pages/api/example.ts
  src/pages/api/resume/[resumeId].ts
  src/pages/api/resume/create.ts
  src/pages/api/resumes/resumes.ts
  src/pages/api/uploadImage/uploadUserImage.ts
  src/types/env.d.ts
  src/types/next-auth.d.ts
  src/types/resumeDataType.ts
  src/utils/.gitkeep
  src/utils/Session.tsx
  src/utils/database.ts
  tsconfig.json
Labels: enhancement

#24 Feat/resume api
  src/app/loading.tsx
  src/app/page.tsx
  src/components/client/main/ResumeCard.tsx
  src/components/client/main/ResumeCardList.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/main/ResumeCardLoad.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/resume/create.ts
  src/pages/api/resumes/resumes.ts
  src/types/next-auth.d.ts
  src/types/resumeDataType.ts
Labels: enhancement

#25 feat: 데이트픽커 오류 해결
  src/components/client/ui/DatePickerComponent.tsx
Labels: documentation

#26 데이트피커 수정 완료
  src/app/page.tsx
  src/components/client/main/ResumeCard.tsx
  src/components/client/main/ResumeCardList.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/ui/DatePickerComponent.tsx
  src/types/resumeDataType.ts
Labels: documentation

#27 Feat:데이터 삽입 진행중
  src/app/[resumeId]/page.tsx
  src/app/create/page.tsx
  src/components/server/Profile.tsx
Labels: documentation

#28 feat:데이터 수정중
  package-lock.json
  package.json
  src/app/[resumeId]/page.tsx
  src/components/server/Introduce.tsx
  src/components/server/Skill.tsx
  src/components/server/Skillset.tsx
  src/components/server/Study.tsx
  src/components/server/resume/Experience.tsx
  src/components/server/resume/ExperienceTitle.tsx
  src/components/server/resume/Introduce.tsx
  src/components/server/resume/Profile.tsx
  src/components/server/resume/Skill.tsx
  src/components/server/resume/Skillset.tsx
  src/components/server/resume/Titlename.tsx
  tailwind.config.js
Labels: documentation

#29 Feat/resume api
  .eslintrc.json
  src/app/[resumeId]/(resumeId)/edit/page.tsx
  src/app/resume/[resumeId]/edit/page.tsx
  src/app/resume/[resumeId]/layout.tsx
  src/app/resume/[resumeId]/page.tsx
  src/app/resume/create/layout.tsx
  src/app/resume/create/page.tsx
  src/components/client/auth/GithubLoginBtn.tsx
  src/components/client/main/ResumeCard.tsx
  src/components/client/main/ResumeCardList.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/ui/Btn.tsx
  src/components/client/ui/DatePickerComponent.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/ui/Header.tsx
  src/pages/api/auth/[...nextauth].ts
  src/types/resumeDataType.ts
  src/utils/AuthorizedAccess.tsx
Labels: enhancement

#30 feat: 이력서 데이터 삽입 작업 완료
  src/app/resume/[resumeId]/layout.tsx
  src/app/resume/[resumeId]/page.tsx
  src/app/resume/create/layout.tsx
  src/components/client/resumeEdit/DatePickerComponent.tsx
  src/components/server/resume/Categories.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/CategoryPeriod.tsx
  src/components/server/resume/Experience.tsx
  src/components/server/resume/ExperienceTitle.tsx
  src/components/server/resume/Introduce.tsx
  src/components/server/resume/Skillset.tsx
  src/components/server/resume/Titlename.tsx
Labels: documentation

#31 feat: 이력서 스타일 수정 완료
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/server/resume/Categories.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/Introduce.tsx
  src/components/server/resume/Profile.tsx
  src/components/server/resume/Skill.tsx
  src/components/server/resume/Skillset.tsx
  src/components/server/resume/Titlename.tsx
Labels: documentation

#33 fix: access control 오류 수정
  src/app/resume/create/page.tsx
  src/app/resume/edit/page.tsx
  src/app/resume/layout.tsx
  src/app/resume/page.tsx
Labels: bug, enhancement
