Repository Subang-Study/devshare, pull requests merged in 2023-09, with the labels that each got.

#47 프로필 부분 스타일 수정
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/server/resume/Introduce.tsx
  src/components/server/resume/Profile.tsx
Labels: fix

#48 Design/design fix
  src/app/favicon.ico
  src/components/client/main/ResumeCard.tsx
  src/components/client/main/ResumeCardList.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/ui/Logo.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/Profile.tsx
  src/components/server/resume/Skill.tsx
  src/components/server/resume/Skillset.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: design

#49 refactor:Input 컴포넌트 제작 및 Txt컴포넌트 옵션 수정
  .gitignore
  src/components/client/main/ResumeCard.tsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/client/ui/Input.tsx
  src/components/client/ui/InputError.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/CategoryPeriod.tsx
  src/components/server/resume/Profile.tsx
Labels: refactor

#50 refactor:Input 컴포넌트 제작 및 Txt컴포넌트 옵션 수정
  src/components/client/main/ResumeCard.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/client/ui/InputError.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/CategoryPeriod.tsx
  src/components/server/resume/Profile.tsx
  src/components/server/resume/Skill.tsx
  src/components/server/resume/Titlename.tsx
Labels: refactor

#51 resume file 정리및 디자인패턴 적용
  src/components/client/resume/ResumeDetail.tsx
  src/components/server/resume/Categories.tsx
  src/components/server/resume/Category.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/CategoryPeriod.tsx
  src/components/server/resume/Introduce.tsx
  src/components/server/resume/Skillset.tsx
  src/components/server/resume/Titlename.tsx
Labels: refactor

#52 Feat/form refactoring
  src/app/loading.tsx
  src/components/Editor/CategoryDetails.tsx
  src/components/Editor/CategoryEditor.tsx
  src/components/Editor/ResumeEditor.tsx
  src/components/Editor/Skill.tsx
  src/components/Editor/UserProfileInputs.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeEdit/CategoryForm.tsx
  src/components/client/resumeEdit/DatePickerComponent.tsx
  src/components/client/resumeEdit/StackBox.tsx
  src/components/client/resumeEdit/TechStackForm.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserImageUploadButton.tsx
  src/components/client/ui/InputError.tsx
  src/components/client/ui/Sorting.tsx
  src/lib/constants/regex.ts
Labels: refactor
