Repository Subang-Study/devshare, pull requests merged in 2023-08, with the labels that each got.

#35 이력서 작성 버튼 완료
  src/components/client/auth/UserMenu.tsx
  src/components/client/resumeld/UserImageUploadButton.tsx
  src/components/server/resume/Profile.tsx
  src/pages/api/resume/create.ts
Labels: documentation

#37 Fix/image upload
  next.config.js
  src/app/resume/edit/page.tsx
  src/components/client/auth/UserMenu.tsx
  src/components/client/resume/ResumeDetail.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/resumeld/UserImageUploadButton.tsx
  src/components/server/resume/Profile.tsx
  src/types/resumeDataType.ts
Labels: enhancement

#38 fix: input error 컴포넌트 추가 및 수정
  src/components/client/resumeld/UserInfoForm.tsx
  src/components/client/ui/InputError.tsx
Labels: enhancement

#41 fix: input-error 컴포넌트 오류 수정
  src/components/client/ui/InputError.tsx
Labels: fix

#42 fix: input-error 컴포넌트 오류 수정
  src/components/client/ui/InputError.tsx
Labels: fix

#43 Feat/auth 스켈레톤 & userinfo 유효성 작업 완료
  src/app/auth/loading.tsx
  src/components/client/resumeld/UserInfoForm.tsx
Labels: documentation

#44 fix: image-upload 업로드 시 저장될 파일 이름 뒤에 업로드시간 추가 수정
  src/components/client/resumeld/CreateProfile.tsx
Labels: fix

#45 feat: card 내용 추가및 디자인 변경
  src/components/client/main/ResumeCard.tsx
  src/components/server/resume/Profile.tsx
Labels: documentation

#46 feat: resume페이지 react-query 적용
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/resume/edit/page.tsx
  src/app/resume/page.tsx
  src/components/client/resume/ResumeDetail.tsx
  src/components/client/resume/ResumeOwnerBtns.tsx
  src/components/client/resumeEdit/CategoryDetails.tsx
  src/components/client/resumeld/CreateProfile.tsx
  src/components/client/ui/Txt.tsx
  src/components/server/resume/CategoryDetails.tsx
  src/components/server/resume/Profile.tsx
  src/components/server/resume/Skill.tsx
  src/components/server/resume/Skillset.tsx
  src/lib/api/post.ts
  src/pages/api/resume/[resumeId].ts
  src/utils/ReactQueryProvider.tsx
  src/utils/getQueryClient.ts
Labels: enhancement
